import Navbar from './components/navbar';
import './globals.css';
import SandParticles from './Utils/SandParticles';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <link
        href="https://fonts.googleapis.com/css2?family=Black+Ops+One&display=swap"
        rel="stylesheet"
      />
      <body className="font-blackOps">
        <div className="relative z-20">
          <Navbar />
        </div>
        <div className="relative z-10">
          <SandParticles />
          {children}
        </div>
      </body>
    </html>
  );
}
